export type IWorksheet = {
    empID: number;
    empCd: string;
    empName: string;
    deptId: number;
    deptCd: string;
    deptDs: string;
    trnDate: Date;
    timeIn: Date;
    timeOut: Date;
    nh: number;
    oT1: number;
    oT2: number;
    oT3: number;
    missTime: number;
    brkHrs: number;
    lateEntryHrs: number;
    earlyExitHrs: number;
    reason: number;
    reasonName: string;
    multipleReason: string;
    rColor: string;
    edited: boolean;
    editedBy: number;
    editedOn: Date;
    remarks: string;
    empRemarks: null;
    wr: number;
    shift: number;
    wrName: string;
    shiftName: string;
    shiftIN: Date;
    shiftOUT: Date;
    shiftOutNextDay: boolean;
    offDay: boolean;
    holiday: boolean;
    nextDay: boolean;
    approved: boolean;
    leExcusedHrs: number;
    eeExcusedHrs: number;
    eeExcuseReason: number;
    leExcuseReason: number;
    eeExcuseReasonDs: string;
    leExcuseReasonDs: string;
    graceLE: number;
    graceEE: number;
    isSpecialLeaveInHrs: boolean;
    specialLeaveHrType: null;
}

export type IWorksheetModel = {
    empID: number;
    empCd: string;
    empName: string;
    deptId: number;
    deptCd: string;
    deptDs: string;
    trnDate: string;
    timeIn: string;
    timeOut: string;
    nh: number;
    oT1: number;
    oT2: number;
    oT3: number;
    missTime: number;
    brkHrs: number;
    lateEntryHrs: number;
    earlyExitHrs: number;
    reason: number;
    reasonName: string;
    multipleReason: string;
    rColor: string;
    edited: boolean;
    editedBy: number;
    editedOn: string;
    remarks: string;
    empRemarks: null;
    wr: number;
    shift: number;
    wrName: string;
    shiftName: string;
    shiftIN: string;
    shiftOUT: string;
    shiftOutNextDay: boolean;
    offDay: boolean;
    holiday: boolean;
    nextDay: boolean;
    approved: boolean;
    leExcusedHrs: number;
    eeExcusedHrs: number;
    eeExcuseReason: number;
    leExcuseReason: number;
    eeExcuseReasonDs: string;
    leExcuseReasonDs: string;
    graceLE: number;
    graceEE: number;
    isSpecialLeaveInHrs: boolean;
    specialLeaveHrType: null;
}

export class Worksheet implements IWorksheet {
    empID: number;
    empCd: string;
    empName: string;
    deptId: number;
    deptCd: string;
    deptDs: string;
    trnDate: Date;
    timeIn: Date;
    timeOut: Date;
    nh: number;
    oT1: number;
    oT2: number;
    oT3: number;
    missTime: number;
    brkHrs: number;
    lateEntryHrs: number;
    earlyExitHrs: number;
    reason: number;
    reasonName: string;
    multipleReason: string;
    rColor: string;
    edited: boolean;
    editedBy: number;
    editedOn: Date;
    remarks: string;
    empRemarks: null;
    wr: number;
    shift: number;
    wrName: string;
    shiftName: string;
    shiftIN: Date;
    shiftOUT: Date;
    shiftOutNextDay: boolean;
    offDay: boolean;
    holiday: boolean;
    nextDay: boolean;
    approved: boolean;
    leExcusedHrs: number;
    eeExcusedHrs: number;
    eeExcuseReason: number;
    leExcuseReason: number;
    eeExcuseReasonDs: string;
    leExcuseReasonDs: string;
    graceLE: number;
    graceEE: number;
    isSpecialLeaveInHrs: boolean;
    specialLeaveHrType: null;
}

export type IMachinePunch = {
    isUpdate: boolean;
    empID: number | null;
    empCd: string;
    empName: string;
    deptCD: number | null;
    trnDate: string;
    trnTime: string | null;
    trnType: string | null;
    machinID: number;
    readed: boolean | null;
    uniCode: number;
    trnDtTime: string | null;
    machName: string | null;
    projectID: number;
    project: string | null;
    trnTypeS: string;
    machinePunch: boolean;
    showDeleteBtn: boolean | null;
    inverseMachPunch: boolean;
    showRollbackBtn: boolean;
    terminalType: string;
}

export class MachinePunch {
    isUpdate: boolean = false;
    empID: number | null = 0;
    empCd: string = '';
    empName: string = '';
    deptCD: number | null;
    trnDate: string = '';
    trnTime: string | null;
    trnType: string | null;
    machinID: number = 0;
    readed: boolean | null;
    uniCode: number = 0;
    trnDtTime: string | null;
    machName: string | null;
    machPunchS: string = "";
    projectID: number = 0;
    project: string | null;
    trnTypeS: string = '';
    machinePunch: boolean = false;
    showDeleteBtn: boolean | null;
    inverseMachPunch: boolean = false;
    showRollbackBtn: boolean = false;
    terminalType: string = '';
}
